package gov.va.api.health.vistafhirquery.interactivetests.organization;

import static gov.va.api.health.r4.api.datatypes.ContactPoint.ContactPointSystem.fax;
import static gov.va.api.health.r4.api.datatypes.ContactPoint.ContactPointSystem.phone;

import gov.va.api.health.r4.api.datatypes.Address;
import gov.va.api.health.r4.api.datatypes.CodeableConcept;
import gov.va.api.health.r4.api.datatypes.Coding;
import gov.va.api.health.r4.api.datatypes.ContactPoint;
import gov.va.api.health.r4.api.datatypes.Identifier;
import gov.va.api.health.r4.api.datatypes.Quantity;
import gov.va.api.health.r4.api.elements.Extension;
import gov.va.api.health.r4.api.elements.Meta;
import gov.va.api.health.r4.api.elements.Reference;
import gov.va.api.health.r4.api.resources.Organization;
import gov.va.api.health.vistafhirquery.interactivetests.InteractiveTestContext;
import gov.va.api.health.vistafhirquery.interactivetests.TestContext;
import java.math.BigDecimal;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;

public class OrganizationCreateTest {

  @Test
  @EnabledIfSystemProperty(named = "interactive-tests", matches = "true")
  void organizationCreate() {
    TestContext ctx = new InteractiveTestContext("OrganizationCreateTest");
    ctx.create(
        Organization.builder()
            .meta(Meta.builder().source(ctx.property("site")).build())
            .extension(
                List.of(
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-allowMultipleBedsections")
                        .valueBoolean(true)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-oneOutpatVisitOnBillOnly")
                        .valueBoolean(true)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-ambulatorySurgeryRevenueCode")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.6.301.3")
                                        .code("331")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url("http://va.gov/fhir/StructureDefinition/organization-filingTimeFrame")
                        .valueString("12 MONTHS")
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesInpatClaims")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url("http://va.gov/fhir/StructureDefinition/organization-typeOfCoverage")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.36.8013")
                                        .code("HEALTH INSURANCE")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesAppeals")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-prescriptionRevenueCode")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.6.301.3")
                                        .code("332")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesInquiries")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesOutpatClaims")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesPrecert")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesRxClaims")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesDentalClaims")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-planStandardFilingTimeFrame")
                        .valueQuantity(
                            Quantity.builder()
                                .value(new BigDecimal(365))
                                .unit("DAYS")
                                .system("urn:oid:2.16.840.1.113883.3.8901.3.3558013")
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-willReimburseForCare")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.1")
                                        .code("WILL REIMBURSE")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-signatureRequiredOnBill")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-electronicTransmissionMode")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.38001")
                                        .code("YES-LIVE")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-electronicInsuranceType")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.38009")
                                        .code("MEDICARE")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/via-intermediary")
                        .valueReference(
                            Reference.builder()
                                .reference("Organization/" + ctx.property("payerId"))
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-performingProviderSecondIDTypeCMS1500")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.3558097.8001")
                                        .code("UPIN")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-performingProviderSecondIDTypeUB04")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.3558097.8001")
                                        .code("BLUE CROSS")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-referringProviderSecondIDTypeCMS1500")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.3558097.8001")
                                        .code("BLUE SHIELD")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-referringProviderSecondIDTypeUB04")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.3558097.8001")
                                        .code("CMS-1500")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-attendingRenderingProviderSecondaryIDProfesionalRequired")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-attendingRenderingProviderSecondaryIDInstitutionalRequired")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-printSecTertAutoClaimsLocally")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-printSecMedClaimsWOMRALocally")
                        .valueBoolean(false)
                        .build()))
            .identifier(
                List.of(
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(Coding.builder().code("PROFEDI").build().asList())
                                .build())
                        .value("5555")
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(Coding.builder().code("INSTEDI").build().asList())
                                .build())
                        .value("6666")
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(Coding.builder().code("BIN").build().asList())
                                .build())
                        .value("TESTBIN")
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.68001")
                                        .code("PAYER ID #")
                                        .build()
                                        .asList())
                                .build())
                        .value("123456")
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.68003")
                                        .code("CLAIM OFFICE #")
                                        .build()
                                        .asList())
                                .build())
                        .value("442222")
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.68005")
                                        .code("NAIC CODE")
                                        .build()
                                        .asList())
                                .build())
                        .value("111999")
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.68007")
                                        .code("FED TAXPAYER #")
                                        .build()
                                        .asList())
                                .build())
                        .value("558833")
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(Coding.builder().code("277EDI").build().asList())
                                .build())
                        .value("77777")
                        .build()))
            .active(true)
            .type(
                CodeableConcept.builder()
                    .coding(
                        Coding.builder()
                            .system("http://hl7.org/fhir/ValueSet/organization-type")
                            .code("ins")
                            .display("Insurance Company")
                            .build()
                            .asList())
                    .text("Insurance Company")
                    .build()
                    .asList())
            .name(ctx.property("name"))
            .telecom(
                List.of(
                    ContactPoint.builder().system(phone).value("777-999-4444").build(),
                    ContactPoint.builder().system(fax).value("555-333-4444").build()))
            .address(
                Address.builder()
                    .line(List.of("PO BOX 1798", "REGIONAL CLAIMS OFFICE", "ATTN: MICHAEL"))
                    .city("JACKSONVILLE")
                    .state("FLORIDA")
                    .postalCode("322310014")
                    .build()
                    .asList())
            .contact(
                List.of(
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("APPEAL")
                                        .display("APPEAL")
                                        .build()
                                        .asList())
                                .build())
                        .telecom(
                            ContactPoint.builder()
                                .system(phone)
                                .value("800-727-2220")
                                .build()
                                .asList())
                        .build(),
                    Organization.Contact.builder()
                        .extension(
                            Extension.builder()
                                .url(
                                    "http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/via-intermediary")
                                .valueReference(Reference.builder().display("BILLING").build())
                                .build()
                                .asList())
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "http://terminology.hl7.org/CodeSystem/contactentity-type")
                                        .code("BILL")
                                        .display("BILL")
                                        .build()
                                        .asList())
                                .text("BILL")
                                .build())
                        .telecom(
                            ContactPoint.builder()
                                .system(phone)
                                .value("800-727-2222")
                                .build()
                                .asList())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("DENTALCLAIMS")
                                        .display("DENTALCLAIMS")
                                        .build()
                                        .asList())
                                .text("DENTALCLAIMS")
                                .build())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("INPTCLAIMS")
                                        .display("INPTCLAIMS")
                                        .build()
                                        .asList())
                                .text("INPTCLAIMS")
                                .build())
                        .telecom(
                            List.of(
                                ContactPoint.builder().system(phone).value("813.626.1101").build(),
                                ContactPoint.builder().system(fax).value("800-500-6065").build()))
                        .address(
                            Address.builder()
                                .line(List.of("P.O. BOX 6003"))
                                .city("JACKSONVILLE")
                                .state("FLORIDA")
                                .postalCode("322310014")
                                .build())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("OUTPTCLAIMS")
                                        .display("OUTPTCLAIMS")
                                        .build()
                                        .asList())
                                .text("OUTPTCLAIMS")
                                .build())
                        .telecom(
                            List.of(
                                ContactPoint.builder()
                                    .system(phone)
                                    .value("(787)751-5656")
                                    .build()))
                        .address(
                            Address.builder()
                                .line(List.of("PO BOX 2832"))
                                .city("NEW YORK")
                                .state("NEW YORK")
                                .postalCode("101162832")
                                .build())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("RXCLAIMS")
                                        .display("RXCLAIMS")
                                        .build()
                                        .asList())
                                .text("RXCLAIMS")
                                .build())
                        .address(
                            Address.builder()
                                .line(List.of("PO BOX 14610"))
                                .city("LEXINGTON")
                                .state("KENTUCKY")
                                .postalCode("405121234")
                                .build())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("INQUIRY")
                                        .display("INQUIRY")
                                        .build()
                                        .asList())
                                .text("INQUIRY")
                                .build())
                        .telecom(
                            ContactPoint.builder()
                                .system(phone)
                                .value("800-727-2111")
                                .build()
                                .asList())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("PRECERT")
                                        .display("PRECERT")
                                        .build()
                                        .asList())
                                .text("PRECERT")
                                .build())
                        .telecom(
                            ContactPoint.builder()
                                .system(phone)
                                .value("800-995-4589")
                                .build()
                                .asList())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("VERIFY")
                                        .display("VERIFY")
                                        .build()
                                        .asList())
                                .text("VERIFY")
                                .build())
                        .telecom(
                            ContactPoint.builder()
                                .system(phone)
                                .value("800-727-2223")
                                .build()
                                .asList())
                        .build()))
            .build());
  }
}
