package gov.va.api.health.vistafhirquery.interactivetests.organization;

import static gov.va.api.health.r4.api.datatypes.ContactPoint.ContactPointSystem.fax;
import static gov.va.api.health.r4.api.datatypes.ContactPoint.ContactPointSystem.phone;
import static java.lang.Boolean.parseBoolean;

import gov.va.api.health.r4.api.datatypes.Address;
import gov.va.api.health.r4.api.datatypes.CodeableConcept;
import gov.va.api.health.r4.api.datatypes.Coding;
import gov.va.api.health.r4.api.datatypes.ContactPoint;
import gov.va.api.health.r4.api.datatypes.Identifier;
import gov.va.api.health.r4.api.datatypes.Quantity;
import gov.va.api.health.r4.api.elements.Extension;
import gov.va.api.health.r4.api.elements.Reference;
import gov.va.api.health.r4.api.resources.Organization;
import gov.va.api.health.vistafhirquery.interactivetests.InteractiveTestContext;
import gov.va.api.health.vistafhirquery.interactivetests.TestContext;
import java.math.BigDecimal;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;

public class OrganizationUpdateTest {

  @Test
  @EnabledIfSystemProperty(named = "interactive-tests", matches = "true")
  void organizationUpdate() {
    TestContext ctx = new InteractiveTestContext("OrganizationUpdate");
    ctx.update(
        Organization.builder()
            .id(ctx.property("organizationId"))
            .extension(
                List.of(
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-allowMultipleBedsections")
                        .valueBoolean(true)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-oneOutpatVisitOnBillOnly")
                        .valueBoolean(true)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-ambulatorySurgeryRevenueCode")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.6.301.3")
                                        .code("331")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url("http://va.gov/fhir/StructureDefinition/organization-filingTimeFrame")
                        .valueString(ctx.property("filingTimeFrame"))
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesInpatClaims")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url("http://va.gov/fhir/StructureDefinition/organization-typeOfCoverage")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.36.8013")
                                        .code(ctx.property("typeOfCoverage"))
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesAppeals")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-prescriptionRevenueCode")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.6.301.3")
                                        .code("332")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesInquiries")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesOutpatClaims")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesPrecert")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesRxClaims")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-anotherCompanyProcessesDentalClaims")
                        .valueBoolean(false)
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-planStandardFilingTimeFrame")
                        .valueQuantity(
                            Quantity.builder()
                                .value(new BigDecimal(365))
                                .unit(ctx.property("planStandardFilingTimeFrame"))
                                .system("urn:oid:2.16.840.1.113883.3.8901.3.3558013")
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-willReimburseForCare")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.1")
                                        .code(ctx.property("willReimburseForCare"))
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-signatureRequiredOnBill")
                        .valueBoolean(parseBoolean(ctx.property("signatureRequiredOnBill")))
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-electronicTransmissionMode")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.38001")
                                        .code(ctx.property("electronicTransmissionMode"))
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-electronicInsuranceType")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.38009")
                                        .code(ctx.property("electronicInsuranceType"))
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/via-intermediary")
                        .valueReference(
                            Reference.builder()
                                .reference("Organization/" + ctx.property("payerId"))
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-performingProviderSecondIDTypeCMS1500")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.3558097.8001")
                                        .code("UPIN")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-performingProviderSecondIDTypeUB04")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.3558097.8001")
                                        .code("BLUE CROSS")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-referringProviderSecondIDTypeCMS1500")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.3558097.8001")
                                        .code("BLUE SHIELD")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-referringProviderSecondIDTypeUB04")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.3558097.8001")
                                        .code("CMS-1500")
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-attendingRenderingProviderSecondaryIDProfesionalRequired")
                        .valueBoolean(
                            parseBoolean(
                                ctx.property(
                                    "attendingRenderingProviderSecondaryIDProfesionalRequired")))
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-attendingRenderingProviderSecondaryIDInstitutionalRequired")
                        .valueBoolean(
                            parseBoolean(
                                ctx.property(
                                    "attendingRenderingProviderSecondaryIDInstitutionalRequired")))
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-printSecTertAutoClaimsLocally")
                        .valueBoolean(parseBoolean(ctx.property("printSecTertAutoClaimsLocally")))
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/organization-printSecMedClaimsWOMRALocally")
                        .valueBoolean(parseBoolean(ctx.property("printSecMedClaimsWOMRALocally")))
                        .build()))
            .identifier(
                List.of(
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(Coding.builder().code("PROFEDI").build().asList())
                                .build())
                        .value(ctx.property("profedi"))
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(Coding.builder().code("INSTEDI").build().asList())
                                .build())
                        .value(ctx.property("instedi"))
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(Coding.builder().code("BIN").build().asList())
                                .build())
                        .value(ctx.property("bin"))
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.68001")
                                        .code("PAYER ID #")
                                        .build()
                                        .asList())
                                .build())
                        .value(ctx.property("payerIdNumber"))
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.68003")
                                        .code("CLAIM OFFICE #")
                                        .build()
                                        .asList())
                                .build())
                        .value(ctx.property("claimOfficeNumber"))
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.68005")
                                        .code("NAIC CODE")
                                        .build()
                                        .asList())
                                .build())
                        .value(ctx.property("naicCode"))
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.36.68007")
                                        .code("FED TAXPAYER #")
                                        .build()
                                        .asList())
                                .build())
                        .value(ctx.property("fedTaxpayerNumber"))
                        .build(),
                    Identifier.builder()
                        .type(
                            CodeableConcept.builder()
                                .coding(Coding.builder().code("277EDI").build().asList())
                                .build())
                        .value(ctx.property("277Edi"))
                        .build()))
            .active(true)
            .type(
                CodeableConcept.builder()
                    .coding(
                        Coding.builder()
                            .system("http://hl7.org/fhir/ValueSet/organization-type")
                            .code("ins")
                            .display("Insurance Company")
                            .build()
                            .asList())
                    .text("Insurance Company")
                    .build()
                    .asList())
            .name(ctx.property("name"))
            .telecom(
                List.of(
                    ContactPoint.builder().system(phone).value(ctx.property("phone")).build(),
                    ContactPoint.builder().system(fax).value(ctx.property("fax")).build()))
            .address(
                Address.builder()
                    .line(
                        List.of(
                            ctx.property("addressLine1"),
                            ctx.property("addressLine2"),
                            ctx.property("addressLine3")))
                    .city(ctx.property("addressCity"))
                    .state(ctx.property("addressState"))
                    .postalCode(ctx.property("addressPostalCode"))
                    .build()
                    .asList())
            .contact(
                List.of(
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("APPEAL")
                                        .display("APPEAL")
                                        .build()
                                        .asList())
                                .build())
                        .telecom(
                            ContactPoint.builder()
                                .system(phone)
                                .value(ctx.property("appealsContactPhone"))
                                .build()
                                .asList())
                        .build(),
                    Organization.Contact.builder()
                        .extension(
                            Extension.builder()
                                .url(
                                    "http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/via-intermediary")
                                .valueReference(Reference.builder().display("BILLING").build())
                                .build()
                                .asList())
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "http://terminology.hl7.org/CodeSystem/contactentity-type")
                                        .code("BILL")
                                        .display("BILL")
                                        .build()
                                        .asList())
                                .text("BILL")
                                .build())
                        .telecom(
                            ContactPoint.builder()
                                .system(phone)
                                .value(ctx.property("billingContactPhone"))
                                .build()
                                .asList())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("DENTALCLAIMS")
                                        .display("DENTALCLAIMS")
                                        .build()
                                        .asList())
                                .text("DENTALCLAIMS")
                                .build())
                        .telecom(
                            List.of(
                                ContactPoint.builder()
                                    .system(phone)
                                    .value(ctx.property("dentalClaimsContactPhone"))
                                    .build()))
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("INPTCLAIMS")
                                        .display("INPTCLAIMS")
                                        .build()
                                        .asList())
                                .text("INPTCLAIMS")
                                .build())
                        .telecom(
                            List.of(
                                ContactPoint.builder()
                                    .system(phone)
                                    .value(ctx.property("inptClaimsContactPhone"))
                                    .build(),
                                ContactPoint.builder()
                                    .system(fax)
                                    .value(ctx.property("inptClaimsContactFax"))
                                    .build()))
                        .address(
                            Address.builder()
                                .line(
                                    List.of(
                                        ctx.property("inptClaimsAddressLine1"),
                                        ctx.property("inptClaimsAddressLine2"),
                                        ctx.property("inptClaimsAddressLine3")))
                                .city(ctx.property("inptClaimsAddressCity"))
                                .state(ctx.property("inptClaimsAddressState"))
                                .postalCode(ctx.property("inptClaimsAddressPostalCode"))
                                .build())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("OUTPTCLAIMS")
                                        .display("OUTPTCLAIMS")
                                        .build()
                                        .asList())
                                .text("OUTPTCLAIMS")
                                .build())
                        .telecom(
                            List.of(
                                ContactPoint.builder()
                                    .system(phone)
                                    .value(ctx.property("outptClaimsPhone"))
                                    .build()))
                        .address(
                            Address.builder()
                                .line(
                                    List.of(
                                        ctx.property("outptClaimsAddressLine1"),
                                        ctx.property("outptClaimsAddressLine2"),
                                        ctx.property("outptClaimsAddressLine3")))
                                .city(ctx.property("outptClaimsAddressCity"))
                                .state(ctx.property("outptClaimsAddressState"))
                                .postalCode(ctx.property("outptClaimsAddressPostalCode"))
                                .build())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("RXCLAIMS")
                                        .display("RXCLAIMS")
                                        .build()
                                        .asList())
                                .text("RXCLAIMS")
                                .build())
                        .telecom(
                            List.of(
                                ContactPoint.builder()
                                    .system(phone)
                                    .value(ctx.property("rxClaimsPhone"))
                                    .build()))
                        .address(
                            Address.builder()
                                .line(List.of("PO BOX 14610"))
                                .city("LEXINGTON")
                                .state("KENTUCKY")
                                .postalCode("405121234")
                                .build())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("INQUIRY")
                                        .display("INQUIRY")
                                        .build()
                                        .asList())
                                .text("INQUIRY")
                                .build())
                        .telecom(
                            ContactPoint.builder()
                                .system(phone)
                                .value(ctx.property("inquiryPhone"))
                                .build()
                                .asList())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("PRECERT")
                                        .display("PRECERT")
                                        .build()
                                        .asList())
                                .text("PRECERT")
                                .build())
                        .telecom(
                            ContactPoint.builder()
                                .system(phone)
                                .value(ctx.property("precertPhone"))
                                .build()
                                .asList())
                        .build(),
                    Organization.Contact.builder()
                        .purpose(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system(
                                            "https://va.gov/fhir/CodeSystem/organization-contactType")
                                        .code("VERIFY")
                                        .display("VERIFY")
                                        .build()
                                        .asList())
                                .text("VERIFY")
                                .build())
                        .telecom(
                            ContactPoint.builder()
                                .system(phone)
                                .value(ctx.property("verifyPhone"))
                                .build()
                                .asList())
                        .build()))
            .build());
  }
}
