package gov.va.api.health.vistafhirquery.interactivetests.coverageeligibilityresponse;

import static gov.va.api.health.r4.api.resources.CoverageEligibilityResponse.Outcome.complete;
import static java.lang.Boolean.parseBoolean;
import static java.lang.Double.parseDouble;

import gov.va.api.health.r4.api.datatypes.CodeableConcept;
import gov.va.api.health.r4.api.datatypes.Coding;
import gov.va.api.health.r4.api.datatypes.Identifier;
import gov.va.api.health.r4.api.datatypes.Money;
import gov.va.api.health.r4.api.datatypes.Period;
import gov.va.api.health.r4.api.datatypes.Quantity;
import gov.va.api.health.r4.api.elements.Extension;
import gov.va.api.health.r4.api.resources.Coverage;
import gov.va.api.health.r4.api.resources.CoverageEligibilityResponse;
import gov.va.api.health.r4.api.resources.Organization;
import gov.va.api.health.r4.api.resources.Patient;
import gov.va.api.health.vistafhirquery.interactivetests.InteractiveTestContext;
import gov.va.api.health.vistafhirquery.interactivetests.TestContext;
import java.math.BigDecimal;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;

public class CoverageEligibilityResponseCreateForPatientTest {

  @Test
  @EnabledIfSystemProperty(named = "interactive-tests", matches = "true")
  void coverageEligibilityResponseWrite() {
    TestContext ctx = new InteractiveTestContext("CoverageEligibilityResponseCreateForPatient");
    ctx.create(
        CoverageEligibilityResponse.builder()
            .resourceType("CoverageEligibilityResponse")
            .extension(
                List.of(
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-militaryInfoStatus")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.365.128001")
                                        .code(ctx.property("militaryInfoStatus"))
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-militaryEmploymentStatus")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.365.128002")
                                        .code(ctx.property("militaryEmploymentStatus"))
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-militaryAffiliation")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.365.128003")
                                        .code(ctx.property("militaryAffiliation"))
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-militaryPersonnelDescription")
                        .valueString(ctx.property("militaryPersonnelDescription"))
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-militaryRank")
                        .valueCodeableConcept(
                            CodeableConcept.builder()
                                .coding(
                                    Coding.builder()
                                        .system("urn:oid:2.16.840.1.113883.3.8901.3.1.365.128005")
                                        .code(ctx.property("militaryRank"))
                                        .build()
                                        .asList())
                                .build())
                        .build(),
                    Extension.builder()
                        .url(
                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-healthCareCode")
                        .extension(
                            List.of(
                                Extension.builder()
                                    .url("diagnosisCode")
                                    .valueCodeableConcept(
                                        CodeableConcept.builder()
                                            .coding(
                                                Coding.builder()
                                                    .system("http://hl7.org/fhir/sid/icd-9-cm")
                                                    .code(ctx.property("diagnosisCode"))
                                                    .build()
                                                    .asList())
                                            .build())
                                    .build(),
                                Extension.builder()
                                    .url("diagnosisCodeQualifier")
                                    .valueString(ctx.property("diagnosisCodeQualifier"))
                                    .build(),
                                Extension.builder()
                                    .url("primaryOrSecondary")
                                    .valueString(ctx.property("primaryOrSecondary"))
                                    .build()))
                        .build()))
            .identifier(
                List.of(
                    Identifier.builder()
                        .type(CodeableConcept.builder().text("MSH-10").build())
                        .value(ctx.property("MSH-10"))
                        .build(),
                    Identifier.builder()
                        .type(CodeableConcept.builder().text("MSA-3").build())
                        .value(ctx.property("MSA-3"))
                        .build()))
            .status(CoverageEligibilityResponse.Status.valueOf(ctx.property("status")))
            .purpose(List.of(CoverageEligibilityResponse.Purpose.valueOf("benefits")))
            .patient(
                ctx.urlsFor(Patient.class)
                    .reference(ctx.property("patient"))
                    .identifier(
                        Identifier.builder()
                            .type(
                                CodeableConcept.builder()
                                    .coding(Coding.builder().code("MB").build().asList())
                                    .build())
                            .value("1234")
                            .build()))
            .servicedDate(ctx.property("servicedDate"))
            .created(ctx.property("created"))
            ._request(
                Extension.builder()
                    .url("http://hl7.org/fhir/StructureDefinition/data-absent-reason")
                    .valueCodeableConcept(
                        CodeableConcept.builder()
                            .coding(
                                Coding.builder()
                                    .system(
                                        "http://terminology.hl7.org/CodeSystem/data-absent-reason")
                                    .code("unsupported")
                                    .display("Unsupported")
                                    .build()
                                    .asList())
                            .text("Unsupported")
                            .build())
                    .build())
            .outcome(complete)
            .insurer(ctx.urlsFor(Organization.class).reference(ctx.property("insurer")))
            .insurance(
                CoverageEligibilityResponse.Insurance.builder()
                    .coverage(
                        ctx.urlsFor(Coverage.class).reference(ctx.property("insuranceCoverage")))
                    .inforce(parseBoolean(ctx.property("insuranceInforce")))
                    .benefitPeriod(
                        Period.builder()
                            .start(ctx.property("insuranceBenefitPeriodStart"))
                            .end(ctx.property("insuranceBenefitPeriodEnd"))
                            .build())
                    .extension(
                        Extension.builder()
                            .url(
                                "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-effectiveDate")
                            .valueDateTime(ctx.property("insuranceEffectiveDate"))
                            .build()
                            .asList())
                    .item(
                        CoverageEligibilityResponse.Item.builder()
                            .extension(
                                List.of(
                                    Extension.builder()
                                        .url(
                                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-requestedServiceType")
                                        .valueCodeableConcept(
                                            CodeableConcept.builder()
                                                .coding(
                                                    Coding.builder()
                                                        .system(
                                                            "2.16.840.1.113883.3.8901.3.1.280312.888002")
                                                        .code(ctx.property("requestedServiceType"))
                                                        .build()
                                                        .asList())
                                                .build())
                                        .build(),
                                    Extension.builder()
                                        .url(
                                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-coverageCategory")
                                        .valueCodeableConcept(
                                            CodeableConcept.builder()
                                                .coding(
                                                    Coding.builder()
                                                        .system(
                                                            "2.16.840.1.113883.3.8901.3.1.3558032.8003")
                                                        .code(ctx.property("coverageCategory"))
                                                        .build()
                                                        .asList())
                                                .build())
                                        .build(),
                                    Extension.builder()
                                        .url(
                                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-healthcareServicesDelivery")
                                        .extension(
                                            List.of(
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-benefitQuantity")
                                                    .valueQuantity(
                                                        Quantity.builder()
                                                            .value(
                                                                BigDecimal.valueOf(
                                                                    parseDouble(
                                                                        ctx.property(
                                                                            "healthcareServicesDeliveryBenefitQuantity"))))
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-quantityQualifier")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "2.16.840.1.113883.3.8901.3.1.3658027.8003")
                                                                    .code(
                                                                        ctx.property(
                                                                            "quantityQualifier"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-sampleSelectionModulus")
                                                    .valueString(
                                                        ctx.property("sampleSelectionModulus"))
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-unitsOfMeasurement")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "2.16.840.1.113883.3.8901.3.1.3658027.8005")
                                                                    .code(
                                                                        ctx.property(
                                                                            "unitsOfMeasurement"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-timePeriods")
                                                    .valueDecimal(
                                                        BigDecimal.valueOf(
                                                            parseDouble(
                                                                ctx.property("timePeriods"))))
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-timePeriodQualifier")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "2.16.840.1.113883.3.8901.3.1.3658027.8007")
                                                                    .code(
                                                                        ctx.property(
                                                                            "timePeriodQualifier"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-deliveryFrequency")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "2.16.840.1.113883.3.8901.3.1.3658027.8008")
                                                                    .code(
                                                                        ctx.property(
                                                                            "deliveryFrequency"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-deliveryPattern")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "2.16.840.1.113883.3.8901.3.1.3658027.8009")
                                                                    .code(
                                                                        ctx.property(
                                                                            "deliveryPattern"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build()))
                                        .build(),
                                    Extension.builder()
                                        .url(
                                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberAdditionalInfo")
                                        .extension(
                                            List.of(
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberPlaceOfService")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "2.16.840.1.113883.3.8901.3.1.3658029.8002")
                                                                    .code(
                                                                        ctx.property(
                                                                            "subscriberPlaceOfService"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberQualifier")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "2.16.840.1.113883.3.8901.3.1.3658029.8004")
                                                                    .code(
                                                                        ctx.property(
                                                                            "subscriberQualifier"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberInjuryCode")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "2.16.840.1.113883.3.8901.3.1.3658029.8005")
                                                                    .code(
                                                                        ctx.property(
                                                                            "subscriberInjuryCode"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberInjuryCategory")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "2.16.840.1.113883.3.8901.3.1.3658029.8006")
                                                                    .code(
                                                                        ctx.property(
                                                                            "subscriberInjuryCategory"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberInjuryText")
                                                    .valueString(
                                                        ctx.property("subscriberInjuryText"))
                                                    .build()))
                                        .build(),
                                    Extension.builder()
                                        .url(
                                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberDate")
                                        .extension(
                                            List.of(
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberDatePeriod")
                                                    .valuePeriod(
                                                        Period.builder()
                                                            .start(
                                                                ctx.property(
                                                                    "subscriberDatePeriod"))
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberDateKind")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "urn:oid:2.16.840.1.113883.3.8901.3.1.36580288.8003")
                                                                    .code(
                                                                        ctx.property(
                                                                            "subscriberDateKind"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build()))
                                        .build(),
                                    Extension.builder()
                                        .url(
                                            "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberReferenceId")
                                        .extension(
                                            List.of(
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberReferenceIdValue")
                                                    .valueString(
                                                        ctx.property("subscriberReferenceIdValue"))
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberReferenceIdQualifier")
                                                    .valueCodeableConcept(
                                                        CodeableConcept.builder()
                                                            .coding(
                                                                Coding.builder()
                                                                    .system(
                                                                        "2.16.840.1.113883.3.8901.3.1.36580291.8003")
                                                                    .code(
                                                                        ctx.property(
                                                                            "subscriberReferenceIdQualifier"))
                                                                    .build()
                                                                    .asList())
                                                            .build())
                                                    .build(),
                                                Extension.builder()
                                                    .url(
                                                        "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-subscriberReferenceIdDescription")
                                                    .valueString(
                                                        ctx.property(
                                                            "subscriberReferenceIdDescription"))
                                                    .build()))
                                        .build()))
                            .category(
                                CodeableConcept.builder()
                                    .coding(
                                        Coding.builder()
                                            .system(
                                                "urn:oid:2.16.840.1.113883.3.8901.3.1.36580292.8001")
                                            .code(ctx.property("itemCategory"))
                                            .build()
                                            .asList())
                                    .build())
                            .productOrService(
                                CodeableConcept.builder()
                                    .coding(
                                        Coding.builder()
                                            .system(ctx.property("itemProductOrServiceSystem"))
                                            .code(ctx.property("itemProductOrServiceCode"))
                                            .build()
                                            .asList())
                                    .build())
                            .modifier(
                                CodeableConcept.builder()
                                    .coding(
                                        Coding.builder()
                                            .system(
                                                "urn:oid:2.16.840.1.113883.3.8901.3.1.3658002.18003")
                                            .code(ctx.property("itemModifier"))
                                            .build()
                                            .asList())
                                    .build()
                                    .asList())
                            .excluded(parseBoolean(ctx.property("itemExcluded")))
                            .description(ctx.property("itemDescription"))
                            .network(
                                CodeableConcept.builder()
                                    .coding(
                                        Coding.builder()
                                            .system(
                                                "urn:oid:2.16.840.1.113883.3.8901.3.1.36580033.8001")
                                            .code(ctx.property("itemNetwork"))
                                            .build()
                                            .asList())
                                    .build())
                            .unit(
                                CodeableConcept.builder()
                                    .coding(
                                        Coding.builder()
                                            .system(
                                                "urn:oid:2.16.840.1.113883.3.8901.3.1.3658002.8003")
                                            .code(ctx.property("itemUnit"))
                                            .build()
                                            .asList())
                                    .build())
                            .term(
                                CodeableConcept.builder()
                                    .coding(
                                        Coding.builder()
                                            .system(
                                                "urn:oid:2.16.840.1.113883.3.8901.3.1.3658002.8007")
                                            .code(ctx.property("itemTerm"))
                                            .build()
                                            .asList())
                                    .build())
                            .benefit(
                                CoverageEligibilityResponse.Benefit.builder()
                                    .extension(
                                        List.of(
                                            Extension.builder()
                                                .url(
                                                    "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-benefitQuantity")
                                                .valueQuantity(
                                                    Quantity.builder()
                                                        .value(
                                                            BigDecimal.valueOf(
                                                                parseDouble(
                                                                    ctx.property(
                                                                        "benefitBenefitQuantity"))))
                                                        .build())
                                                .build(),
                                            Extension.builder()
                                                .url(
                                                    "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-benefitPercent")
                                                .valueQuantity(
                                                    Quantity.builder()
                                                        .value(
                                                            BigDecimal.valueOf(
                                                                parseDouble(
                                                                    ctx.property(
                                                                        "benefitPercent"))))
                                                        .build())
                                                .build(),
                                            Extension.builder()
                                                .url(
                                                    "http://va.gov/fhir/StructureDefinition/coverageEligibilityResponse-benefitQuantityCode")
                                                .valueCodeableConcept(
                                                    CodeableConcept.builder()
                                                        .coding(
                                                            Coding.builder()
                                                                .system(
                                                                    "2.16.840.1.113883.3.8901.3.1.3658002.801")
                                                                .code(
                                                                    ctx.property(
                                                                        "benefitQuantityCode"))
                                                                .build()
                                                                .asList())
                                                        .build())
                                                .build()))
                                    .type(
                                        CodeableConcept.builder()
                                            .coding(
                                                Coding.builder()
                                                    .system(
                                                        "urn:oid:2.16.840.1.113883.3.8901.3.1.3658002.8002")
                                                    .code(ctx.property("itemType"))
                                                    .build()
                                                    .asList())
                                            .build())
                                    .allowedMoney(
                                        Money.builder()
                                            .value(
                                                BigDecimal.valueOf(
                                                    parseDouble(ctx.property("itemAllowedMoney"))))
                                            .build())
                                    .build()
                                    .asList())
                            .authorizationRequired(
                                parseBoolean(ctx.property("itemAuthorizationRequired")))
                            .build()
                            .asList())
                    .build()
                    .asList())
            .build());
  }
}
